version: '3'
services:
  app:
    container_name: messenger-server
    restart: always
    build: .
    ports:
      - '3000:3000'
    environment: 
      - SERVER_PORT=3000
      - MONGO_URL=mongodb://mongo:27017
    volumes:
      - ./:/code
    external_links:
      - mongo
      - redis
  mongo:
    container_name: messenger-mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
  redis:
    container_name: messenger-redis
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redisdb:/data
    environment:
      - ALLOW_EMPTY_PASSWORD=no #just for dev
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL 
volumes:
  mongodb:
  mongodb_config:
  redisdb: